### ISSUE TITLE
Does this project works with PHP 8.1?

### ISSUE THREAD

**Issue by jessicastcotripal** [dbmaker-go/laravel-dbmaker#2]
I'm having the following error after execute "php artisan server" with PHP 8.1.2. Before, with PHP 7.4.2 everything worked fine:

 PHP Fatal error:  Declaration of DBMaker\ODBC\DBMakerODBCPdoStatement::fetchAll($how = null, $class_name = null, $ctor_args = null) must be compatible with PDOStatement::fetchAll(int $mode = PDO::FETCH_DEFAULT, mixed ...$args): array in /home/user/Documents/project/api/vendor/dbmaker/laravel-odbc/src/DBMakerODBCPdoStatement.php on line 79

**Comment by jessicastcotripal** [comment]
Hi!

Thank you so much for your help, it solved my issue.

Now I'm getting a new error:

`{
    "message": "PDO object is uninitialized",
    "exception": "Error",
    "file": "/home/user/Documentos/myDocs/Project/API/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
    "line": 425,
    "trace": [
        {
            "file": "/home/user/Documentos/myDocs/Project/API/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 425,
            "function": "setFetchMode",
            "class": "PDOStatement",
            "type": "->"
        },
        {
            "file": "/home/user/Documentos/myDocs/Project/API/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 368,
            "function": "prepared",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
...
}
` 
I also noticed an error when executed php artisan serve OR  php -m:
`[Wed Nov  9 11:52:18 2022] PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_odbc.so' (tried: /usr/lib64/php/modules/pdo_odbc.so (/usr/lib64/php/modules/pdo_odbc.so: undefined symbol: pdo_parse_params), /usr/lib64/php/modules/pdo_odbc.so.so (/usr/lib64/php/modules/pdo_odbc.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

This pdo_odbc.so came from https://github.com/dbmaker-go/php_ext/releases/download/1.0.0/php_dbmaker-5.4-7.3-Linux2_x86_64.tgz (following the documentation https://packagist.org/packages/dbmaker/laravel-odbc#1.3.0)

Is there any other package where I can get it from?

**Comment by erycson** [comment]
> Unable to load dynamic library 'pdo_odbc.so'

This error says that the PHP ODBC module could not be initialized. Try to confirm if the installed version is correct, or if the location of pdo_odbc.so is correct, if it was actually installed, etc.

**Comment by jessicastcotripal** [comment]
This pdo_odbc.so came from this project: https://github.com/dbmaker-go/php_ext/releases/download/1.0.0/php_dbmaker-5.4-7.3-Linux2_x86_64.tgz 

Is there any other package where I can get it from?

Steps to reproduce can be found in the follow documentation: https://packagist.org/packages/dbmaker/laravel-odbc#1.3.0

# wget https://github.com/dbmaker-go/php_ext/releases/download/1.0.0/php_dbmaker-5.4-7.3-Linux2_x86_64.tgz
# tar zxvf php_dbmaker-5.4-7.3-Linux2_x86_64.tgz
# mv php_dbmaker/bundle/pdo_odbc.ini /etc/php.d/20-pdo-odbc.ini
# mv php_dbmaker/bundle/pdo_odbc.so /usr/lib64/php/modules/pdo-odbc.so
# php -m

I also have tried to copy php_dbmaker/bundle/pdo_odbc.so  to /usr/lib64/php/modules/pdo_odbc.so but this leads to others erros

![Captura de tela de 2022-11-10 08-44-15](https://user-images.githubusercontent.com/88110167/201083046-5c867efb-764a-4191-bd13-ce5a129d0de6.png)

**Comment by erycson** [comment]
> wget https://github.com/dbmaker-go/php_ext/releases/download/1.0.0/php_dbmaker-5.4-7.3-Linux2_x86_64.tgz

Are you using the ODBC driver for this project? If yes, it doesn't work in PHP 8.1, use normal ODBC driver while they don't release a new version

**Comment by jessicastcotripal** [comment]
Thanks for the reply.

The ODBC issue was solved by using the original library instead of the one provided in this project.

However, we are still getting the "PDO object is uninitialized" error (it starts after we have changed the code in src/DBMakerODBCPdoStatement.php and src/DBMakerPdo.php) 

` "message": "PDO object is uninitialized", "exception": "Error", "file": "/home/user/Documentos/myDocs/Project/API/vendor/laravel/framework/src/Illuminate/Database/Connection.php", "line": 425, "trace": [ { "file":"/home/user/Documentos/myDocs/Project/API/vendor/laravel/framework/src/Illuminate/Database/Connection.php", "line": 425, "function": "setFetchMode", "class": "PDOStatement", "type": "->" }, { "file": "/home/user/Documentos/myDocs/Project/API/vendor/laravel/framework/src/Illuminate/Database/Connection.php", "line": 368, "function": "prepared", "class": "Illuminate\\Database\\Connection", "type": "->" }, ... }`

![image](https://user-images.githubusercontent.com/88110167/201190939-127e1666-a37a-4206-b597-e63f64b41958.png)

**Comment by araujodev** [comment]
Im trying connect in ubuntu by dmconfig.ini present in folder /home/dbmaker/5.4 but i retrieve this error: 
```
odbc_connect(): SQL error: [unixODBC][Driver Manager]Data source name not found, and no default driver specified, SQL state IM002 in SQLConnect
``` @erycson

**Comment by jessicastcotripal** [comment]
I solved my issue!
Thank you @erycson !!!!

@araujodev  I followed all the steps as @erycson has told me before, and I've found the same error you mentioned.

Before PHP 8 I was using  on .ENV
`DB_DSN=DRIVER={DBMAKER};DATABASE=name_database;`

This Dbmaker variable was loaded in the /etc/odbcinst.ini file:
`[DBMaker]
Description=ODBC for DBMaker 5.4
Driver=/home/dbmaker/5.4/lib/so/libdmapic.so
FileUsage=1
`

And now  in PHP 8, this was the only way I've found to make it work:
`DB_DSN="odbc:DRIVER=/home/dbmaker/5.4/lib/so/libdmapic.so;DATABASE=name_database;"`

**Comment by araujodev** [comment]
Thanks @jessicastcotripal.

**Comment by araujodev** [comment]
Hi @jessicastcotripal , 

Im try connect by MacOSX for local development and Im receive this error: 

{
    "error": "odbc_connect(): SQL error: [unixODBC][Driver Manager]Can't open lib '/opt/dbmaker/bundle/libdmapic.so' : file not found, SQL state 01000 in SQLConnect"
}

**Comment by jessicastcotripal** [comment]
Hi!

You need to make sure that you referenced file is correct (in the correct path)

In your terminal, type: "ls -lah /opt/dbmaker/bundle/libdmapic.so" and see if the lib is realy there. In my case, it was in $DBMAKER/lib/so/ directory

**Comment by jessicastcotripal** [comment]
> Hi @araujodev !
> 
> You need to make sure that you referenced file is correct (in the correct path)
> 
> In your terminal, type: "ls -lah /opt/dbmaker/bundle/libdmapic.so" and see if the lib is realy there. In my case, it was in $DBMAKER/lib/so/ directory

In adiction, if the file exist, check the permissions.
